version: "3"

services:
  certbot-service:
    container_name: certbot_container
    image: certbot/certbot:v2.11.0
    restart: unless-stopped
    volumes:
      - ${SCENARIO_SERVER_CERTCONFIGDIR}/conf:/etc/letsencrypt
      - ${SCENARIO_SERVER_CERTCONFIGDIR}/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
