version: "3"

services:
  woda-structr-server:
    container_name: ${SCENARIO_STRUCTR_CONTAINER}
    build: "./structr"
    image: ${SCENARIO_STRUCTR_IMAGE}
    user: "${SCENARIO_STRUCTR_UID}:${SCENARIO_STRUCTR_GID}"
    restart: unless-stopped
    env_file: ".env"
    ports:
      - ${SCENARIO_RESOURCE_STRUCTR_HTTP}:8082
      - ${SCENARIO_RESOURCE_STRUCTR_HTTPS}:8083
    volumes:
      - ${SCENARIO_SRC_STRUCTR_DIR}/db/:/var/lib/structr/db/
      - ${SCENARIO_SRC_STRUCTR_DIR}/files/:/var/lib/structr/files/
      - ${SCENARIO_SRC_STRUCTR_DIR}/layouts/:/var/lib/structr/layouts/
      - ${SCENARIO_SRC_STRUCTR_DIR}/logs/:/var/lib/structr/logs/
      - ${SCENARIO_SRC_STRUCTR_DIR}/sessions/:/var/lib/structr/sessions/
      - ${SCENARIO_SRC_STRUCTR_DIR}/snapshots/:/var/lib/structr/snapshots/
      - ${SCENARIO_SERVER_EAMDDIR}:/EAMD.ucp
      - ${SCENARIO_SERVER_EAMDDIR}/Components/tla/EAMD/UcpComponentSupport/1.0.0/src/sh:/var/lib/structr/scripts/
    environment:
      - PROXY_ADDRESS_FORWARDING=true
networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORKNAME}
