pipeline {
    agent {
        docker {
            image 'once.sh-builder'
            args '-v once_jenkins:/var/dev -v once_jenkins_home:/var/jenkins_home -w /var/dev --entrypoint "" --user root'
            reuseNode true
        }
    }

    options {
        ansiColor('xterm')
    }
    
    stages {
        stage('Cleanup & update') {
            steps {
                sh '''#!/usr/bin/bash
                    rm -rf results
                    mkdir -p results
                    cd /var/dev/Once.2023 && git reset --hard && git checkout dev && git pull
                    '''
            }
        }
        stage('Deploy dev/neom with latest structr server') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: "agent.jenkins", keyFileVariable: 'keyfile')]) {
                    sh '''#!/usr/bin/bash
                        cd /var/dev/Once.2023/qa/deploy
                        alias ssh="ssh -o StrictHostKeyChecking=no -i $keyfile"
                        ./deploy-scenario.sh dev-neom remove
                        ./deploy-scenario.sh dev-neom
                        ./deploy-scenario.sh dev-neom test > results/dev-neom.log
                    '''
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'results/*', onlyIfSuccessful: true
        }
    }
}