@startuml
skinparam state {
    BackgroundColor<<State>> LightBlue
    BorderColor<<State>> Black
    BackgroundColor<<Action>> LightGreen
    BorderColor<<Action>> Black
}

state "Inited" as Inited <<State>>
state "Running" as Running <<State>>
state "Stopped" as Stopped <<State>>

[*] --> Inited : init
Inited --> Running : up
Stopped --> Running : start,up
Running --> Stopped : stop
Running --> Inited : down
Stopped --> Inited : down
Running -[dotted]-> [*] : deinit(+down)
Inited --> [*] : deinit
Stopped -[dotted]-> [*] : deinit(+down)

Inited --> Inited : init,\nupdateconfig,\ntest
Running --> Running : init,\nupdateconfig,\ntest
Stopped --> Stopped : init,\nupdateconfig,\ntest

@enduml
