@startuml
skinparam state {
    BackgroundColor<<State>> LightBlue
    BorderColor<<State>> Black
    BackgroundColor<<Action>> LightGreen
    BorderColor<<Action>> Black
}

state "Inited" as Inited <<State>>
state "Running" as Running <<State>>
state "Stopped" as Stopped <<State>>

[*] --> Inited : init
[*] --> Running : up(+init)
Inited --> Running : up
Stopped --> Running : start,up
Running --> Stopped : stop
Running --> Inited : down
Stopped --> Inited : down
Running --> [*] : deinit
Inited --> [*] : deinit
Stopped --> [*] : deinit

any_state --> any_state : init
any_state --> any_state : updateconfig
any_state --> any_state : test

@enduml
