pipeline {
    agent {
        docker {
            image 'once.sh-server'
            args '-v once_woda_qa:/var/dev  -v once_jenkins_home:/var/jenkins_home -w /var/dev --entrypoint "" --user root'
            reuseNode true
        }
    }

    environment {
        TREE = 'com/neom/EAM'
        NAME = 'com.neom.EAM'
    }

    options {
        timeout(time: 5, unit: 'MINUTES') 
        ansiColor('xterm')
    }
    
    stages {
        stage('Cleanup & update') {
            steps {
                sh '''#!/usr/bin/bash
                    rm -rf results
                    mkdir -p results
                    cd /var/dev && ( git clone 2cuBitbucket:donges/eamd.ucp.git || true )
                    cd eamd.ucp && git reset --hard && git checkout $BRANCH && git pull
                    cd /var/dev && ( git clone 2cuGitHub:Cerulean-Circle-GmbH/Once.2023.git || true )
                    cd Once.2023 && git reset --hard && git checkout dev && git pull
                    '''
            }
        }
        stage('Start WODA') {
            steps {
                sh '''#!/usr/bin/bash
                    source ~/config/user.env && oo mode.dev && oo update
                    once init
                    once domain.set localhost
                    once stage next
                    once stage next
                    once stage next
                    once start
                    '''
            }
        }
        stage('Check WODA status') {
            steps {
                sh '''#!/usr/bin/bash
                    source ~/config/user.env
                    once status
                    '''
            }
        }
        stage('Test WODA') {
            steps {
                sh '''#!/usr/bin/bash
                    source ~/config/user.env
                    once test
                    '''
            }
        }
    }
    //post {
    //    always {
    //        archiveArtifacts artifacts: 'results/*', onlyIfSuccessful: true
    //    }
    //}
}