pipeline {
    agent {
        docker {
            image 'once.sh-builder'
            args '-v once_jenkins:/var/dev  -v jenkins_jenkins_home:/var/jenkins_home -w /var/dev --entrypoint "" --user root'
            reuseNode true
        }
    }

    stages {
        stage('Print Checkout') {
            steps {
                script {
                    def scmVars = checkout scm
                    echo "Checked out branch: ${scmVars.GIT_BRANCH}"
                }
            }
        }

        stage('build image once.sh-builder') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    git config --global --add safe.directory "*"
                    source ~/config/user.env
                    cd Units/docker-images/once.sh.ubuntu.22.04-builder
                    ./devTool docker.build
                    '''
            }
        }

        stage('build image once.sh-server') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    cd Units/docker-images/once.sh.ubuntu.22.04-server
                    ./devTool docker.build
                    '''
            }
        }

        stage('build & deploy image once.sh-server multi-branch') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKER_IO_CRED', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_LOGIN')]) {
                    sh '''#!/usr/bin/bash
                        set -e
                        source ~/config/user.env
                        cd Units/docker-images/once.sh.ubuntu.22.04-server
                        ./devTool docker.buildx.use
                        docker login -u ${DOCKER_LOGIN} --password ${DOCKER_PW}
                        ./devTool docker.buildx.push
                        '''
                }
            }
        }

        stage('release image once.sh-server multi-branch') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKER_IO_CRED', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_LOGIN')]) {
                    sh '''#!/bin/bash
                        set -e
                        source ~/config/user.env
                        cd Units/docker-images/once.sh.ubuntu.22.04-server
                        BRANCH=`echo $GIT_BRANCH | sed "s;origin/;;"`
                        if [[ "$RELEASE_CMD" == "release" ]]; then
                            if [[ $BRANCH != "main" ]]; then
                                echo "Should be the main branch but is: $BRANCH"
                                exit 1
                            else
                                cd Units/docker-images/once.sh.ubuntu.22.04-server
                                ./devTool docker.buildx.use
                                docker login -u ${DOCKER_LOGIN} --password ${DOCKER_PW}
                                ./devTool docker.buildx.push.latest
                            fi
                        elif [ ! -z "$RELEASE_CMD" ]; then
                            echo "RELEASE_CMD has the wrong value: $RELEASE_CMD"
                            exit 1
                        fi
                        '''
                }
            }
        }
    }
}
