pipeline {
    agent {
        docker {
            image 'once.sh-builder'
            args '-v once_jenkins:/var/dev  -v jenkins_jenkins_home:/var/jenkins_home -w /var/dev --entrypoint "" --user root'
            reuseNode true
        }
    }

    environment {
        TREE = 'com/neom'
        NAME = 'com.neom'
    }

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Print Checkout') {
            steps {
                script {
                    def scmVars = checkout scm
                    echo "Checked out branch: ${scmVars.GIT_BRANCH}"
                }
            }
        }

        stage('Cleanup & update') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    Units/cleanupAndUpdateEAMD.sh dev/neom
                    find $WORKSPACE -name "_*" | xargs rm -rf
                    mkdir -p $WORKSPACE/_results
                    '''
            }
        }
        stage('Check branches') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    oo mode.dev
                    oo update
                    cd /var/dev/EAMD.ucp
                    export LOG_DEVICE=$WORKSPACE/_results/branch.txt
                    config save log
                    oo branches.check feature/neom dev/neom 6a7a3d3
                    export LOG_DEVICE=/dev/stdout
                    config save log
                    cat $WORKSPACE/_results/branch.txt
                    cat $WORKSPACE/_results/branch.txt | ansi2html > $WORKSPACE/_results/branch.html
                    '''
            }
        }
        stage('Create class svg (wavi)') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    TMP=/tmp/${TREE}
                    SOURCE=/var/dev/EAMD.ucp/Components/${TREE}
                    source ~/config/user.env
                    oo mode.dev
                    oo update
                    rm -rf $TMP
                    mkdir -p $TMP
                    rsync -a --include='*.js' --include='*/' --exclude='*' $SOURCE/ $TMP/
                    wavi $TMP $WORKSPACE/_results/$NAME.wavi.svg
                    '''
            }
        }
        stage('Create class svg (puml)') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    oo mode.dev
                    oo update
                    cd ./Units/generatePUML
                    rm -rf _*
                    npm install
                    ./generatePUML.js /var/dev/EAMD.ucp/Components/com/neom
                    export PLANTUML_LIMIT_SIZE=18192
                    plantuml _test.puml -tsvg
                    plantuml _test.puml -tpng
                    mv _test.svg $WORKSPACE/_results/$NAME.puml.svg
                    mv _test.png $WORKSPACE/_results/$NAME.puml.png
                    '''
            }
        }
        stage('Static analysis of EAMD') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    oo mode.dev
                    oo update
                    cd ./Units/staticAnalysis
                    ./staticAnalysis.sh /var/dev/EAMD.ucp | tee $WORKSPACE/_results/staticAnalysis.txt
                    '''
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '_results/*', onlyIfSuccessful: true
        }
    }
}
