pipeline {
    agent {
        docker {
            image 'once.sh-server'
            args '-v once_woda_qa:/var/dev  -v jenkins_jenkins_home:/var/jenkins_home -w /var/dev --network once-woda-network --entrypoint "" --user root'
            reuseNode true
        }
    }

    environment {
        TREE = 'com/neom/EAM'
        NAME = 'com.neom.EAM'
    }

    options {
        timeout(time: 5, unit: 'MINUTES')
        ansiColor('xterm')
    }

    stages {
        stage('Cleanup & update (dev/neom)') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    Units/cleanupAndUpdateEAMD.sh dev/neom
                    find $WORKSPACE -name "_*" | xargs rm -rf
                    mkdir -p $WORKSPACE/_results
                    oo mode.dev
                    oo update
                    '''
            }
        }
        stage('Start WODA') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    once init
                    once domain.set localhost
                    once stage next
                    once stage next
                    once stage next
                    once start
                    '''
            }
        }
        stage('Check WODA status (dev/neom)') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    once status
                    '''
            }
        }
        stage('Test WODA') {
            steps {
                sh '''#!/usr/bin/bash
                    set -e
                    source ~/config/user.env
                    source ~/.once
                    echo "MKT: Add environment variables to .once"
                    cat <<EOF >> $ONCE_DEFAULT_SCENARIO/.once
export ONCE_DEFAULT_URL=https://localhost:8443
export ONCE_DIRECT_HTTPS_URL=https://localhost:8443
export ONCE_DEFAULT_UDE_STORE=https://localhost:8443
export ONCE_DEFAULT_URL=https://localhost:8443
export ONCE_DEFAULT_KEYCLOAK_SERVER='{ "realm": "master", "clientId": "shifternetzwerk", "testClient": { "client_id": "mochaAPI", "client_secret": "df37971a-f098-4310-8a62-b238b15c7b35" , "mocha1id": "42b8c48b-34d6-4a33-8c93-5e3782c05a48", "mocha2id": "ccfff6f6-7764-4111-98f3-6bf68d8e4b26", "mocha3id": "92746ce6-d5ce-4127-9e45-30fef19cf7a6" }, "url": "https://test.wo-da.de/auth"}'
EOF
                    echo "MKT: cat $ONCE_DEFAULT_SCENARIO/.once"
                    wc -l $ONCE_DEFAULT_SCENARIO/.once
                    cat $ONCE_DEFAULT_SCENARIO/.once
                    echo "MKT: once test"
                    #cd /var/dev/EAMD.ucp
                    #git status
                    #cat /var/dev/EAMD.ucp/Components/tla/EAM/layer1/Thinglish/Once/4.3.0/test/Once.mocha.test.js
                    mkdir -p $WORKSPACE/_results
                    once test | tee $WORKSPACE/_results/test.log
                    if [ -n "`cat $WORKSPACE/_results/test.log | grep failing`" ]; then
                        echo "FAILING ..."
                        exit 1
                    fi
                    '''
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '_results/*', onlyIfSuccessful: false
        }
    }
}
