version: "3"

services:
  nginx-service:
    container_name: nginx_proxy_container
    image: ${SCENARIO_DOCKER_IMAGENAME}:${SCENARIO_DOCKER_IMAGEVERSION}
    restart: unless-stopped
    volumes:
      - ${SCENARIO_SERVER_CONFIGDIR}:/etc/nginx/conf.d/
      - ${SCENARIO_SERVER_CERTIFICATEDIR}/conf:/etc/letsencrypt
      - ${SCENARIO_SERVER_CERTIFICATEDIR}/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORKNAME}
