version: "3.4"

# TODO: not working with path on docker-compose version <= 1.25.0
# Remove this temporary, when restarting the scenario
volumes:
  service-volume:
    external: ${SCENARIO_DATA_VOLUME_1_EXTERNAL}
    name: ${SCENARIO_DATA_VOLUME_1_PATH}
