version: "3.4"

services:
  nagios-service:
    container_name: ${SCENARIO_NAME}_nagios_container
    image: jasonrivers/nagios:4.5.2
    volumes:
      - ${SCENARIO_DATA_MOUNTPOINT}:/opt/nagios/
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:80"
