services:
  devbox:
    container_name: mims_container
    build:
      context: ../Units/docker-images/once.sh.ubuntu.22.04-devbox
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
        # Ubuntu 22.04 enhanced container with docker-in-docker
        BASE_IMAGE: cruizba/ubuntu-dind:jammy-latest
    restart: unless-stopped
    environment:
      - SHELL=/bin/bash
    volumes:
      # to persist global packages
      - ./devbox.json:/root/.local/share/devbox/global/default/devbox.json
      - ./devbox.lock:/root/.local/share/devbox/global/default/devbox.lock
      # mount users .ssh directory
      - ~/.ssh:/root/.ssh:ro
      # mount workspace
      - ../:/workspace/MIMS
      - ${VAR_DEV:-/dev/null}:/var/dev
      # persist nix-store
      - nix-store:/nix
      # persist docker-in-docker volumes
      - dind-var-lib-docker:/var/lib/docker
    # vscode needs a running container, so we make its shell interactive
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # for being able to run docker-in-docker
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  nix-store:
    external: true
  dind-var-lib-docker:
    external: true
