global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

  metrics:
    address: ":8082"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: __SCENARIO_LETSENCRYPT_EMAIL__
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"

api:
  dashboard: true
  insecure: false  # Make sure the dashboard is secured

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

log:
  level: DEBUG
