services:
  jenkins-service:
    container_name: ${SCENARIO_NAME}_jenkins_container
    image: ${SCENARIO_NAME}_jenkins_image
    restart: always
    hostname: ${SCENARIO_SERVER_HOSTNAME:-jenkins}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SCENARIO_DATA_MOUNTPOINT_1}:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Duser.timezone=Europe/Berlin
    networks:
      - default

networks:
  default:
    external: true
    name: ${SCENARIO_SERVER_NETWORK_NAME}
