version: "3.4"

services:
  nagios-service:
    container_name: ${SCENARIO_NAME}_nagios_container
    image: jasonrivers/nagios:4.5.2
    restart: always
    hostname: ${SCENARIO_SERVER_HOSTNAME:-nagios}
    volumes:
      - ${SCENARIO_DATA_MOUNTPOINT_1}:/opt/nagios/etc
      - ${SCENARIO_DATA_MOUNTPOINT_2}:/opt/nagios/var
      - ${SCENARIO_DATA_MOUNTPOINT_3}:/opt/Custom-Nagios-Plugins
      - ${SCENARIO_DATA_MOUNTPOINT_4}:/opt/nagiosgraph/etc
      - ${SCENARIO_DATA_MOUNTPOINT_5}:/opt/nagiosgraph/var
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:80"
    networks:
      - default

networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORK_NAME}
