version: "3.4"

services:
  nagios-service:
    container_name: ${SCENARIO_NAME}_nagios_container
    image: jasonrivers/nagios:4.5.2
    volumes:
      - ${SCENARIO_DATA_MOUNTPOINT1}:/opt/nagios/etc
      - ${SCENARIO_DATA_MOUNTPOINT2}:/opt/nagios/var
      - ${SCENARIO_DATA_MOUNTPOINT3}:/opt/Custom-Nagios-Plugins
      - ${SCENARIO_DATA_MOUNTPOINT4}:/opt/nagiosgraph/etc
      - ${SCENARIO_DATA_MOUNTPOINT5}:/opt/nagiosgraph/var
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:80"
