version: "3.4"

services:
  gitea-service:
    depends_on:
      - gitea-db
    container_name: ${SCENARIO_NAME}_gitea_container
    image: gitea/gitea:1.22.6
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=giteadb
      - GITEA__database__USER=giteaadm
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_db_passwd
      - GITEA__mailer__ENABLED=${SCENARIO_MAILER_ENABLE}
      - GITEA__mailer__PROTOCOL=${SCENARIO_MAILER_PROTOCOL}
      - GITEA__mailer__SMTP_ADDR=${SCENARIO_MAILER_HOST}
      - GITEA__mailer__SMTP_PORT=${SCENARIO_MAILER_PORT}
      - GITEA__mailer__USE_CLIENT_CERT=${SCENARIO_MAILER_USECLIENTCERT}
      - GITEA__mailer__USER=${SCENARIO_MAILER_USER}
      - GITEA__mailer__PASSWD=${SCENARIO_MAILER_PASSWD}
      - GITEA__mailer__FROM=${SCENARIO_MAILER_FROM}
      # Will be available in 1.23.0
      # - GITEA_RUNNER_REGISTRATION_TOKEN_FILE=/run/secrets/gitea_runner_registration_token
      - GITEA_CUSTOM=/data/gitea
    restart: always
    hostname: ${SCENARIO_SERVER_HOSTNAME:-gitea}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${SCENARIO_DATA_MOUNTPOINT_1}:/data
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:3000"
      - "${SCENARIO_RESOURCE_SSHPORT}:22"
    secrets:
      - gitea_db_passwd
      # - gitea_runner_registration_token
    networks:
        default:
          aliases:
            - gitea

  gitea-db:
    container_name: ${SCENARIO_NAME}_gitea_db_container
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=giteaadm
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=giteadb
    volumes:
      - ${SCENARIO_DATA_MOUNTPOINT_2}:/var/lib/postgresql/data
    secrets:
      - gitea_db_passwd
    networks:
      - default

  gitea-action-runner:
    depends_on:
      - gitea-service
    container_name: ${SCENARIO_NAME}_gitea_action_runner_container
    image: gitea/act_runner:latest
    restart: always
    environment:
      - GITEA_INSTANCE_URL=http://${SCENARIO_SERVER_HOSTNAME:-gitea}:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN_FILE=/run/secrets/gitea_runner_registration_token
      - GITEA_RUNNER_NAME=act_runner_latest
      - CONFIG_FILE=/config.yaml
    volumes:
      # Volume for storing .runner file. Without it will cause action runner to re-register as a new runner!
      - ${SCENARIO_DATA_MOUNTPOINT_3}:/data
      - ./runner_config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - gitea_runner_registration_token
    networks:
      - default

networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORK_NAME}

# https://docs.docker.com/reference/compose-file/services/#secrets
secrets:
  gitea_runner_registration_token:
    # Token can be written to file via: docker exec ${SCENARIO_NAME}_gitea_container su -c 'gitea actions generate-runner-token' git
    file: ${SCENARIO_SRC_SECRETSDIR}/gitea_runner_registration_token.txt
  gitea_db_passwd:
    file: ${SCENARIO_SRC_SECRETSDIR}/gitea_db_passwd.txt
