version: "3.4"

services:
  gitea-service:
    depends_on:
      - gitea-db
    container_name: ${SCENARIO_NAME}_gitea_container
    image: gitea/gitea:1.22.6
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=giteadb
      - GITEA__database__USER=giteaadm
      - GITEA__database__PASSWD__FILE=/run/secrets/gitea_db_passwd
    restart: always
    hostname: ${SCENARIO_SERVER_HOSTNAME:-gitea}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${SCENARIO_DATA_MOUNTPOINT_1}:/data
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:3000"
      - "${SCENARIO_RESOURCE_SSHPORT}:22"
    secrets:
      - gitea_db_passwd
    networks:
      - default

  gitea-db:
    container_name: ${SCENARIO_NAME}_gitea_db_container
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=giteaadm
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=giteadb
    volumes:
      - ${SCENARIO_DATA_MOUNTPOINT_2}:/var/lib/postgresql/data
    secrets:
      - gitea_db_passwd
    networks:
      - default

networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORK_NAME}

# https://docs.docker.com/reference/compose-file/services/#secrets
secrets:
  gitea_db_passwd:
    file: ${SCENARIO_SRC_SECRETSDIR}/gitea_db_passwd.txt
