version: "3.4"

services:
  gitea-service:
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.docker.network: ${SCENARIO_TRAEFIK_NETWORK_NAME}

networks:
  proxy:
    external: true
    name: ${SCENARIO_TRAEFIK_NETWORK_NAME}
