version: "3"

services:
  once.sh:
    container_name: ${SCENARIO_ONCE_CONTAINER}
    image: donges/once:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/snapd.socket:/run/snapd.socket
      - var_dev:/var/dev
    ports:
      - ${SCENARIO_RESOURCE_ONCE_HTTP}:8080
      - ${SCENARIO_RESOURCE_ONCE_HTTPS}:8443
      - ${SCENARIO_RESOURCE_ONCE_SSH}:22
      - ${SCENARIO_RESOURCE_ONCE_REVERSEPROXY_HTTP}:5002
      - ${SCENARIO_RESOURCE_ONCE_REVERSEPROXY_HTTPS}:5005
    environment:
      ONCE_DOCKER_HTTP_PORT: ${SCENARIO_RESOURCE_ONCE_HTTP}
      ONCE_DOCKER_HTTPS_PORT: ${SCENARIO_RESOURCE_ONCE_HTTPS}
      ONCE_DOCKER_REVERSE_PROXY_HTTP_PORT: ${SCENARIO_RESOURCE_ONCE_REVERSEPROXY_HTTP}
      ONCE_DOCKER_REVERSE_PROXY_HTTPS_PORT: ${SCENARIO_RESOURCE_ONCE_REVERSEPROXY_HTTPS}
  woda-structr-server:
    container_name: ${SCENARIO_STRUCTR_CONTAINER}
    build: './structr'
    image: woda-structr-server2.1.4
    user: "${SCENARIO_STRUCTR_UID}:${SCENARIO_STRUCTR_GID}"
    restart: unless-stopped
    env_file: '.env'
    ports:
      - ${SCENARIO_RESOURCE_STRUCTR_HTTP}:8082
      - ${SCENARIO_RESOURCE_STRUCTR_HTTPS}:8083
    volumes:
      - ${SCENARIO_STRUCTR_DIR}/db/:/var/lib/structr/db/
      - ${SCENARIO_STRUCTR_DIR}/files/:/var/lib/structr/files/
      - ${SCENARIO_STRUCTR_DIR}/layouts/:/var/lib/structr/layouts/
      - ${SCENARIO_STRUCTR_DIR}/logs/:/var/lib/structr/logs/
      - ${SCENARIO_STRUCTR_DIR}/sessions/:/var/lib/structr/sessions/
      - ${SCENARIO_STRUCTR_DIR}/snapshots/:/var/lib/structr/snapshots/
      - var_dev:/var/dev
    environment:
      - PROXY_ADDRESS_FORWARDING=true
volumes:
  var_dev:
#networks:
#  default:
#    external: false
#    name: ${SCENARIO_NAME}-woda-network
