services:
  mailpit:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${SCENARIO_TRAEFIK_NETWORK_NAME}"

      # Router: root domain only, no PathPrefix stripping for '/'
      - "traefik.http.routers.mailpit_${SCENARIO_NAME}.rule=Host(`${SCENARIO_TRAEFIK_MAILPIT_URL}`)"
      - "traefik.http.routers.mailpit_${SCENARIO_NAME}.entrypoints=websecure"
      - "traefik.http.routers.mailpit_${SCENARIO_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.mailpit_${SCENARIO_NAME}-headers.headers.customrequestheaders.Host=${SCENARIO_TRAEFIK_MAILPIT_URL}"
      - "traefik.http.routers.mailpit_${SCENARIO_NAME}.middlewares=mailpit_${SCENARIO_NAME}-headers"
      - "traefik.http.services.mailpit_${SCENARIO_NAME}.loadbalancer.server.port=8025"

networks:
  traefik:
    external: true
    name: ${SCENARIO_TRAEFIK_NETWORK_NAME}
