services:
  jenkins-service:
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.docker.network: ${SCENARIO_TRAEFIK_NETWORK_NAME}
      # Router for /jenkins
      traefik.http.routers.jenkins.rule: Host(`${SCENARIO_SERVER_NAME}`) && PathPrefix(`/jenkins`)
      traefik.http.routers.jenkins.entrypoints: websecure
      traefik.http.routers.jenkins.tls.certresolver: letsencrypt

networks:
  proxy:
    external: true
    name: ${SCENARIO_TRAEFIK_NETWORK_NAME}
