version: "3.4"

services:
  jenkins-service:
    container_name: ${SCENARIO_NAME}_jenkins_container
    image: ${SCENARIO_NAME}_jenkins_image
    restart: always
    hostname: ${SCENARIO_SERVER_HOSTNAME:-jenkins}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SCENARIO_DATA_MOUNTPOINT1}:/var/jenkins_home
    ports:
      - "${SCENARIO_RESOURCE_HTTPPORT}:8080"
      - "${SCENARIO_RESOURCE_AGENTPORT}:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - default

networks:
  default:
    external:
      name: ${SCENARIO_SERVER_NETWORK_NAME}
